# Generated by Django 5.2 on 2025-05-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='print_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
